name: PREVISION CI

on:
  pull_request:
    branches: [ main ]  # Trigger for PRs to main branch

env:
  IOS_PROVISION: ${{ secrets.IOS_PROVISION }}

jobs:
  ios_build:
    runs-on: macOS-latest
    steps:
    - name: Generate fastlane provision
      run: |
        cd ios && echo "$IOS_PROVISION" > Fastlane.mobileprovision.asc
        gpg -d --passphrase "$ANDROID_KEYSTORE_PASSWORD" --batch Fastlane.mobileprovision.asc > ios/Fastlane.mobileprovision.asc