name: PREVISION CI

on:
  pull_request:
    branches: [ main ]  # Trigger for PRs to main branch

env:
  FLEETBASE_KEY: ${{ secrets.FLEETBASE_KEY }}
  GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
  ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
  ANDROID_RELEASE_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
  IOS_PROVISION: ${{ secrets.IOS_PROVISION }}

jobs:
  ios_build:
    runs-on: macOS-latest
    steps:
    - name: Generate fastlane provision
      working-directory: ios
      run: |
        echo "$IOS_PROVISION" > Fastlane.mobileprovision