name: PREVISION CI

on:
  pull_request:
    branches: [ main ]  # Trigger for PRs to main branch

env:
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

jobs:
  ios_build:
    runs-on: macOS-latest
    steps:
     - name: Setup Ruby
       uses: ruby/setup-ruby@v1
       with:
          ruby-version: '2.7.4'

     - name: Setup Fastlane
       working-directory: ./ios
       run: bundle install
    
     - name: Install Fastlane
       working-directory: ./ios
       run:  fastlane beta