name: PREVISION CI

on:
  pull_request:
    branches: [ main ]  # Trigger for PRs to main branch

env:
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      

jobs:
  ios_build:
    runs-on: macOS-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CocoaPods
      run: sudo gem install cocoapods -v '1.14.3'

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
          ruby-version: '2.7.4'

    - name: Setup Fastlane
      run:  cd ios && bundle install

    - name: Setup app store api key
      run: echo ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENTS }} > ./ios/AuthKey.p8

    - name: Install Fastlane
      run:  cd ios && fastlane beta
