name: Fleetbase Navigator App CI

on:
  pull_request:
    branches: [ main ]  # Trigger for PRs to main branch

env:
  FLEETBASE_KEY: ${{ secrets.FLEETBASE_KEY }}
  GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
  ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
  ANDROID_RELEASE_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
jobs:
  android_build:
    runs-on: ubuntu-latest
    steps:
 
    - name: Generate release keystore
      run: |
        echo "$ANDROID_RELEASE_KEYSTORE" > release.keystore.asc
        mkdir -p android/app/
        gpg --decrypt --batch --passphrase "$ANDROID_KEYSTORE_PASSWORD" release.keystore.asc


