name: PREVISION CI

on:
  pull_request:
    branches: [ main ]  # Trigger for PRs to main branch

env:
  IOS_PROVISION: ${{ secrets.IOS_PROVISION }}

jobs:
  ios_build:
    runs-on: macOS-latest
    steps:
     - name: Setup Ruby
       uses: ruby/setup-ruby@v1
       with:
          ruby-version: '2.7.4'

     - name: Setup Fastlane
       run: bundle install
    
     - name: Install Fastlane
       run:  fastlane beta
       env:
         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}