name: PREVISION CI

on:
  pull_request:
    branches: [ main ]  # Trigger for PRs to main branch

jobs:
  ios_build:
    runs-on: macOS-latest
    steps:
     - name: Set up ruby env
       uses: ruby/setup-ruby@v1
       with:
         ruby-version: 3.2.2
         bundler-cache: true
     - name: Select Xcode
       run: sudo Xcode-select -switch /Applications/Xcode_14.2.app/Contents/Developer
     - name: Build
       run: xcodebuild clean build -workspace NavigatorApp.xcworkspace -scheme <Your_proj_scheme> -destination 'platform=iOS Simulator,name=iPhone 14 Pro example,OS=16.2'

     - name: Setup Fastlane
       working-directory: ./ios
       run: bundle install
    
     - name: Install Fastlane
       working-directory: ./ios
       run:  fastlane beta

       env:
         APPLE_ID: '${{ secrets.APPLE_ID }}'
         IOS_IDENTIFIER: '${{ secrets.IOS_IDENTIFIER }}'
         TEAM_ID: '${{ secrets.TEAM_ID }}'
         FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
         FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
         MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
         GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'