name: Fleetbase Navigator App CI

on:
  pull_request:
    branches: [ main ]  # Trigger for PRs to main branch

env:
  FLEETBASE_KEY: ${{ secrets.FLEETBASE_KEY }}
  GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
  ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
  ANDROID_RELEASE_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install

  android_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: |
        echo "$GOOGLE_SERVICES_JSON" > google-services.json
        mkdir -p android/app/src  
        mv google-services.json android/app/src
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle' 
        java-version: '17'
        
    - name: Run Jetify
      run: npx jetify

    - name: Cache Gradle Wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

    - name: Cache Gradle Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-caches-
    - name: Make Gradlew Executable
      run: cd android && chmod +x ./gradlew

    - name: Generate release keystore
      run: |
        echo "$ANDROID_RELEASE_KEYSTORE" > release.keystore.asc
        gpg -d --passphrase "$ANDROID_KEYSTORE_PASSWORD" --batch release.keystore.asc > android/app/release.keystore

    - name: Build Android
      run: cd android && ./gradlew assembleDebug

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
          ruby-version: '2.7.4'

    - name: Setup Fastlane
      working-directory: ./android
      run: bundle install

    - name: Install Fastlane
      working-directory: ./android
      run:  fastlane beta

  ios_build:
    runs-on: macOS-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install

    - name: Install CocoaPods
      run: sudo gem install cocoapods -v '1.14.3'

    - name: Install Algolia Gem
      run: |
        gem install algolia

    - name: Install iOS pods
      run: cd ios && pod install

    - name: Build iOS
      run: npx react-native run-ios --configuration Release
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
          ruby-version: '2.7.4'

    - name: Setup Fastlane
      working-directory: ./ios
      run: bundle install
    
    - name: Install Fastlane
      working-directory: ./ios
      run:  fastlane beta
